
export type AlleleHeight = 'A' | 'a';
export type AlleleShape = 'B' | 'b';

export type Genotype = string; // e.g., "AaBb", "AABB", "aabb"

export interface Phenotype {
  height: 'High' | 'Short';
  shape: 'Round' | 'Wrinkled';
}

export interface Seed {
  id: string;
  genotype: Genotype;
  phenotype: Phenotype;
  isRevealed: boolean; // For "blind box" mechanic. Only phenotype is visible initially unless tested.
  isTester?: boolean; // Special seed for test crosses (aabb)
}

export interface GardenPlot {
  id: number;
  parent1: Seed | null;
  parent2: Seed | null;
  offspring: Seed[] | null; // Changed to array for multiple offspring
  status: 'empty' | 'planted' | 'growing' | 'ready';
  progress: number; // 0 to 100
  isLocked: boolean;
  unlockPrice: number;
}

export interface Customer {
  id: string;
  name: string;
  description: string; // generated by AI
  requirements: {
    phenotype?: Phenotype;
    genotype?: Genotype; // "I need purebreds!"
    quantity: number;
  };
  timeLeft: number; // seconds
  maxTime: number;
  reward: number;
  dialogue?: string;
}

export interface GameState {
  money: number;
  reputation: number; // 0-100
  day: number;
  inventory: Seed[];
  plots: GardenPlot[];
  customers: Customer[];
  isPaused: boolean;
  selectedSeedId: string | null;
  tutorialStep: number; // 0 = done, 1-N = active steps
}
